### ISSUE TITLE
GitHub Issue Template for Releases

### ISSUE THREAD

**Issue by ChaelCodes** [ChaelCodes/jekyll-twitch#26]
Create two GitHub issue templates. A default one, and one for creating new releases. The one for releases should include all the steps associated with releasing a new gem version from CONTRIBUTING.md. The default one just needs a description header and a `closes #` placeholder for the issue it closes.

**Comment by LittleBigProgramming** [comment]
Hi 👋 I would like to pick this up! 😄 I can work on it this weekend

**Comment by LittleBigProgramming** [comment]
@ChaelCodes 

The issue here mentions issue templates but based on the mention of a `closes #` placeholder, do we want a pull requests templates instead? Just thought I'd check. 😄 🎃


_Additional Research_
From what I've been trying to do so far and the research I've conducted I'm not sure that release templates are possible right now. I thought it would be nice to prompt the next steps of a release within there but it doesn't seem to be possible. 

Please see https://stackoverflow.com/questions/56798253/release-template-for-github and the [Github doc](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes) for Configuring automatically generated release notes which seems quite limited.


![Screenshot 2022-10-21 at 14 33 56](https://user-images.githubusercontent.com/20643587/197208362-a5735f98-8aa5-461a-9420-1ca74255d0d3.png)

**Comment by ChaelCodes** [comment]
I love the look of those release templates. I'll have to look at that further later.

I wrote this issue while pretty sleep-deprived. I wanted two issue templates, and the inclusion of `closes #` was mistaken.

Eventually, I'll want a PR template too if the repo doesn't have one already.
